import { reddit, type WikiPagePermissionLevel } from '@devvit/web/server';
import packageJson from '../../package.json';
import { ARTEMIS_SETTINGS } from './artemisSettings';
import {
  collateBotStatusSection,
  collateOverallSection,
  collatePostsSection,
  collateSubscribersSection,
} from './artemisStatsCollator';
import {
  hasLegacyStatsArchive,
  hasStatsWikiReadyNotificationBeenSent,
  hasStatsWikiSetupWarningNotificationBeenSent,
  setLegacyStatsArchived,
  setStatsWikiReadyNotificationSent,
  setStatsWikiSetupWarningNotificationSent,
} from './artemisStorage';
import {
  saveLegacyMonthlyPostStats,
  type LegacyMonthlyPostStats,
} from './artemisStatsStorage';
import { timeConvertToString } from './timekeeping';
import { sendModeratorNotification } from './artemisModmail';
import {
  msgModStatisticsFirst,
  msgModStatsWikiSetupProblem,
  wikipageBlank,
  wikipageTemplate,
} from './text';

export const ARTEMIS_STATS_PAGE = 'assistantbot_statistics';
export const ARTEMIS_LEGACY_STATS_PAGE = 'assistantbot_statistics_legacy';
const ARTEMIS_STATS_VERSION = packageJson.version;
const ARTEMIS_DEVVIT_STATS_MARKER = '<!-- Artemis Devvit statistics page -->';
const WIKI_PAGE_MODS_ONLY = 2 as WikiPagePermissionLevel;

type StatsWikiPage = {
  content: string;
  created: boolean;
};

type LegacyStatsArchive = {
  throughDate: string | undefined;
  content: string;
};

function nowSeconds(): number {
  return Math.floor(Date.now() / 1000);
}

function isDevvitStatsPage(content: string): boolean {
  return (
    content.includes(ARTEMIS_DEVVIT_STATS_MARKER) ||
    content.includes('generated by the Devvit port of Artemis') ||
    content.includes(`Artemis v${ARTEMIS_STATS_VERSION}`)
  );
}

function isBlankStatsPlaceholder(content: string): boolean {
  return (
    content.includes('# Statistics by Artemis') &&
    content.includes('This statistics page will be updated after')
  );
}

function shouldArchiveStatsPage(content: string): boolean {
  return (
    content.trim().length > 0 &&
    !isDevvitStatsPage(content) &&
    !isBlankStatsPlaceholder(content)
  );
}

function legacyStatsThroughDate(content: string): string | undefined {
  return content.match(/updated on (\d{4}-\d{2}-\d{2}) UTC/i)?.[1];
}

function legacyArchiveLink(subredditName: string): string {
  return `https://www.reddit.com/r/${subredditName}/wiki/${ARTEMIS_LEGACY_STATS_PAGE}`;
}

async function sendStatsWikiReadyNotification(subredditName: string): Promise<void> {
  if (await hasStatsWikiReadyNotificationBeenSent(subredditName)) {
    return;
  }

  const sent = await sendModeratorNotification({
    subredditName,
    subject: 'Artemis statistics page is ready',
    bodyMarkdown: msgModStatisticsFirst(subredditName),
    logContext: 'statistics page ready',
  });
  if (sent) {
    await setStatsWikiReadyNotificationSent(subredditName, true);
  }
}

export async function sendStatsWikiSetupWarningNotification(
  subredditName: string
): Promise<void> {
  if (
    (await hasStatsWikiReadyNotificationBeenSent(subredditName)) ||
    (await hasStatsWikiSetupWarningNotificationBeenSent(subredditName))
  ) {
    return;
  }

  const sent = await sendModeratorNotification({
    subredditName,
    subject: 'Artemis could not update the statistics wiki',
    bodyMarkdown: msgModStatsWikiSetupProblem(subredditName),
    logContext: 'statistics wiki setup warning',
  });
  if (sent) {
    await setStatsWikiSetupWarningNotificationSent(subredditName, true);
  }
}

function parseCount(value: string): number {
  return Number.parseInt(value.replace(/,/g, ''), 10) || 0;
}

function unformatLegacyFlair(value: string): string {
  const trimmed = value.trim();
  if (trimmed === '*None*') {
    return 'None';
  }

  return trimmed.replace(/^\*\*(.*)\*\*$/, '$1');
}

function parseLegacyMonthlyPostStats(content: string): LegacyMonthlyPostStats[] {
  const months: LegacyMonthlyPostStats[] = [];
  const monthMatches = [...content.matchAll(/^### (\d{4}-\d{2})\s*$/gm)];

  for (const [index, match] of monthMatches.entries()) {
    const month = match[1];
    if (!month || match.index === undefined) {
      continue;
    }

    const nextMatch = monthMatches[index + 1];
    const block = content.slice(
      match.index,
      nextMatch?.index ?? content.length
    );
    const tableStart = block.indexOf(
      '| Post Flair | Number of Submissions | Percentage |'
    );
    if (tableStart < 0) {
      continue;
    }

    const flairCounts: Record<string, number> = {};
    let total = 0;
    const tableLines = block.slice(tableStart).split('\n').slice(2);
    for (const line of tableLines) {
      if (!line.startsWith('|')) {
        break;
      }

      const cells = line
        .split('|')
        .slice(1, -1)
        .map((cell) => cell.trim());
      const flair = cells[0];
      const count = parseCount(cells[1] ?? '');
      if (!flair) {
        continue;
      }

      if (flair === '**Total**') {
        total = count;
      } else {
        flairCounts[unformatLegacyFlair(flair)] = count;
      }
    }

    const inferredTotal = Object.values(flairCounts).reduce(
      (sum, count) => sum + count,
      0
    );
    months.push({
      month,
      total: total || inferredTotal,
      flairCounts,
    });
  }

  return months;
}

async function importLegacyMonthlyPostStats(content: string): Promise<void> {
  await saveLegacyMonthlyPostStats(parseLegacyMonthlyPostStats(content));
}

async function setStatsWikiPageSettings(
  subredditName: string,
  page: string
): Promise<void> {
  try {
    await reddit.updateWikiPageSettings({
      subredditName,
      page,
      listed: false,
      permLevel: WIKI_PAGE_MODS_ONLY,
    });
  } catch (err) {
    console.warn(
      `Artemis Stats Wiki: could not update settings for r/${subredditName}/${page}.`,
      err
    );
  }
}

async function ensureStatsWikiPage(
  subredditName: string
): Promise<StatsWikiPage> {
  try {
    const page = await reddit.getWikiPage(subredditName, ARTEMIS_STATS_PAGE);
    return { content: page.content, created: false };
  } catch {
    const createdPage = await reddit.createWikiPage({
      subredditName,
      page: ARTEMIS_STATS_PAGE,
      content: wikipageBlank(0),
      reason: 'Creating the Artemis statistics wiki page.',
    });

    await setStatsWikiPageSettings(subredditName, ARTEMIS_STATS_PAGE);
    return { content: createdPage.content, created: true };
  }
}

async function loadExistingLegacyArchive(
  subredditName: string
): Promise<LegacyStatsArchive | undefined> {
  try {
    const archivePage = await reddit.getWikiPage(
      subredditName,
      ARTEMIS_LEGACY_STATS_PAGE
    );
    return {
      throughDate: legacyStatsThroughDate(archivePage.content),
      content: archivePage.content,
    };
  } catch {
    return undefined;
  }
}

async function ensureLegacyStatsArchive(
  subredditName: string,
  currentStatsPage: StatsWikiPage
): Promise<LegacyStatsArchive | undefined> {
  const knownArchive = (await hasLegacyStatsArchive(subredditName))
    ? await loadExistingLegacyArchive(subredditName)
    : undefined;
  if (knownArchive) {
    await importLegacyMonthlyPostStats(knownArchive.content);
    return knownArchive;
  }

  const existingArchive = await loadExistingLegacyArchive(subredditName);
  if (existingArchive) {
    await importLegacyMonthlyPostStats(existingArchive.content);
    await setLegacyStatsArchived(subredditName, true);
    return existingArchive;
  }

  if (
    currentStatsPage.created ||
    !shouldArchiveStatsPage(currentStatsPage.content)
  ) {
    return undefined;
  }

  await reddit.createWikiPage({
    subredditName,
    page: ARTEMIS_LEGACY_STATS_PAGE,
    content: currentStatsPage.content,
    reason:
      'Archiving legacy Artemis statistics before Devvit statistics migration.',
  });
  await setStatsWikiPageSettings(subredditName, ARTEMIS_LEGACY_STATS_PAGE);
  await importLegacyMonthlyPostStats(currentStatsPage.content);
  await setLegacyStatsArchived(subredditName, true);

  return {
    throughDate: legacyStatsThroughDate(currentStatsPage.content),
    content: currentStatsPage.content,
  };
}

function buildAnnouncementSection(
  subredditName: string,
  legacyArchive?: LegacyStatsArchive
): string {
  const lines = [
    '*This page is generated by the Devvit port of Artemis. Its statistics entries will vary from the former Python runtime.*',
  ];

  if (legacyArchive) {
    const throughDate = legacyArchive.throughDate
      ? ` through ${legacyArchive.throughDate}`
      : '';
    lines.push(
      '',
      `*Legacy Artemis statistics${throughDate} are archived at [${ARTEMIS_LEGACY_STATS_PAGE}](${legacyArchiveLink(
        subredditName
      )}).*`
    );
  }

  return lines.join('\n');
}

export async function initializeStatsWikiPage(
  subredditName: string
): Promise<void> {
  try {
    const statsPage = await ensureStatsWikiPage(subredditName);
    await ensureLegacyStatsArchive(subredditName, statsPage);
  } catch (err) {
    console.warn(`Artemis Stats Wiki: could not initialize r/${subredditName}.`, err);
    await sendStatsWikiSetupWarningNotification(subredditName);
    throw err;
  }
}

export async function updateStatsWikiPage(
  subredditName: string
): Promise<void> {
  try {
    const compileStart = Date.now();
    const statsPage = await ensureStatsWikiPage(subredditName);
    const legacyArchive = await ensureLegacyStatsArchive(
      subredditName,
      statsPage
    );

    const [overallSection, botStatusSection, postsSection, subscribersSection] =
      await Promise.all([
        collateOverallSection(),
        collateBotStatusSection(),
        collatePostsSection(),
        collateSubscribersSection(),
      ]);

    const content = wikipageTemplate({
      subredditName,
      overallSection,
      botStatusSection,
      postsSection,
      subscribersSection,
      versionNumber: ARTEMIS_STATS_VERSION,
      compileSeconds: ((Date.now() - compileStart) / 1000).toFixed(2),
      updatedAtUtc: timeConvertToString(nowSeconds()),
      announcementSection: buildAnnouncementSection(subredditName, legacyArchive),
      navigationPrefix: '',
    });

    await reddit.updateWikiPage({
      subredditName,
      page: ARTEMIS_STATS_PAGE,
      content,
      reason: `Updating with Devvit statistics data. Retained post snapshots: ${ARTEMIS_SETTINGS.statsPostRetention}.`,
    });
    await sendStatsWikiReadyNotification(subredditName);
  } catch (err) {
    console.warn(`Artemis Stats Wiki: could not update r/${subredditName}.`, err);
    await sendStatsWikiSetupWarningNotification(subredditName);
    throw err;
  }
}

export async function updateStatsWikiPages(
  subredditNames: string[]
): Promise<void> {
  for (const subredditName of subredditNames) {
    await updateStatsWikiPage(subredditName);
  }
}
