import { reddit, type WikiPagePermissionLevel } from '@devvit/web/server';
import { ARTEMIS_SETTINGS } from './artemisSettings';
import { getAppModPermissions, hasPermission } from './artemisModeration';
import {
  collateBotStatusSection,
  collatePostsSection,
  collateSubscribersSection,
  collateTrafficSection,
} from './artemisStatsCollator';
import { timeConvertToString } from './timekeeping';
import { wikipageBlank, wikipageTemplate } from './text';

export const ARTEMIS_STATS_PAGE = 'assistantbot_statistics';
const ARTEMIS_STATS_VERSION = '0.0.0-devvit';
const WIKI_PAGE_MODS_ONLY = 2 as WikiPagePermissionLevel;

function nowSeconds(): number {
  return Math.floor(Date.now() / 1000);
}

async function ensureStatsWikiPage(subredditName: string): Promise<void> {
  try {
    await reddit.getWikiPage(subredditName, ARTEMIS_STATS_PAGE);
    return;
  } catch {
    await reddit.createWikiPage({
      subredditName,
      page: ARTEMIS_STATS_PAGE,
      content: wikipageBlank(0),
      reason: 'Creating the Artemis statistics wiki page.',
    });
  }

  try {
    await reddit.updateWikiPageSettings({
      subredditName,
      page: ARTEMIS_STATS_PAGE,
      listed: false,
      permLevel: WIKI_PAGE_MODS_ONLY,
    });
  } catch (err) {
    console.warn(`Artemis Stats Wiki: could not update settings for r/${subredditName}.`, err);
  }
}

export async function initializeStatsWikiPage(subredditName: string): Promise<void> {
  const permissions = await getAppModPermissions(subredditName);
  if (!hasPermission(permissions, 'wiki')) {
    console.warn(`Artemis Stats Wiki: missing wiki permission on r/${subredditName}.`);
    return;
  }

  await ensureStatsWikiPage(subredditName);
}

export async function updateStatsWikiPage(subredditName: string): Promise<void> {
  const permissions = await getAppModPermissions(subredditName);
  if (!hasPermission(permissions, 'wiki')) {
    console.warn(`Artemis Stats Wiki: missing wiki permission on r/${subredditName}.`);
    return;
  }

  const compileStart = Date.now();
  await ensureStatsWikiPage(subredditName);

  const [botStatusSection, postsSection, subscribersSection] = await Promise.all([
    collateBotStatusSection(),
    collatePostsSection(),
    collateSubscribersSection(),
  ]);

  const content = wikipageTemplate({
    subredditName,
    botStatusSection,
    postsSection,
    subscribersSection,
    trafficSection: collateTrafficSection(),
    versionNumber: ARTEMIS_STATS_VERSION,
    compileSeconds: ((Date.now() - compileStart) / 1000).toFixed(2),
    updatedAtUtc: timeConvertToString(nowSeconds()),
    announcementSection:
      '*This page is generated by the Devvit port of Artemis. Some historical Python-era statistics are not available in this runtime.*',
    navigationPrefix: '',
  });

  await reddit.updateWikiPage({
    subredditName,
    page: ARTEMIS_STATS_PAGE,
    content,
    reason: `Updating with Devvit statistics data. Retained post snapshots: ${ARTEMIS_SETTINGS.statsPostRetention}.`,
  });
}

export async function updateStatsWikiPages(subredditNames: string[]): Promise<void> {
  for (const subredditName of subredditNames) {
    await updateStatsWikiPage(subredditName);
  }
}
