import { reddit, type WikiPagePermissionLevel } from '@devvit/web/server';
import { ARTEMIS_SETTINGS } from './artemisSettings';
import {
  collateBotStatusSection,
  collatePostsSection,
  collateSubscribersSection,
  collateTrafficSection,
} from './artemisStatsCollator';
import { timeConvertToString } from './timekeeping';
import { wikipageBlank, wikipageTemplate } from './text';

export const ARTEMIS_STATS_PAGE = 'assistantbot_statistics';
export const ARTEMIS_LEGACY_STATS_PAGE = 'assistantbot_statistics_legacy';
const ARTEMIS_STATS_VERSION = '0.0.0-devvit';
const ARTEMIS_DEVVIT_STATS_MARKER = '<!-- Artemis Devvit statistics page -->';
const WIKI_PAGE_MODS_ONLY = 2 as WikiPagePermissionLevel;

type StatsWikiPage = {
  content: string;
  created: boolean;
};

type LegacyStatsArchive = {
  throughDate: string | undefined;
};

function nowSeconds(): number {
  return Math.floor(Date.now() / 1000);
}

function isDevvitStatsPage(content: string): boolean {
  return (
    content.includes(ARTEMIS_DEVVIT_STATS_MARKER) ||
    content.includes('generated by the Devvit port of Artemis') ||
    content.includes(`Artemis v${ARTEMIS_STATS_VERSION}`)
  );
}

function isBlankStatsPlaceholder(content: string): boolean {
  return (
    content.includes('# Statistics by Artemis') &&
    content.includes('This statistics page will be updated after')
  );
}

function shouldArchiveStatsPage(content: string): boolean {
  return (
    content.trim().length > 0 &&
    !isDevvitStatsPage(content) &&
    !isBlankStatsPlaceholder(content)
  );
}

function legacyStatsThroughDate(content: string): string | undefined {
  return content.match(/updated on (\d{4}-\d{2}-\d{2}) UTC/i)?.[1];
}

function legacyArchiveLink(subredditName: string): string {
  return `https://www.reddit.com/r/${subredditName}/wiki/${ARTEMIS_LEGACY_STATS_PAGE}`;
}

async function setStatsWikiPageSettings(
  subredditName: string,
  page: string
): Promise<void> {
  try {
    await reddit.updateWikiPageSettings({
      subredditName,
      page,
      listed: false,
      permLevel: WIKI_PAGE_MODS_ONLY,
    });
  } catch (err) {
    console.warn(
      `Artemis Stats Wiki: could not update settings for r/${subredditName}/${page}.`,
      err
    );
  }
}

async function ensureStatsWikiPage(
  subredditName: string
): Promise<StatsWikiPage> {
  try {
    const page = await reddit.getWikiPage(subredditName, ARTEMIS_STATS_PAGE);
    return { content: page.content, created: false };
  } catch {
    const createdPage = await reddit.createWikiPage({
      subredditName,
      page: ARTEMIS_STATS_PAGE,
      content: wikipageBlank(0),
      reason: 'Creating the Artemis statistics wiki page.',
    });

    await setStatsWikiPageSettings(subredditName, ARTEMIS_STATS_PAGE);
    return { content: createdPage.content, created: true };
  }
}

async function loadExistingLegacyArchive(
  subredditName: string
): Promise<LegacyStatsArchive | undefined> {
  try {
    const archivePage = await reddit.getWikiPage(
      subredditName,
      ARTEMIS_LEGACY_STATS_PAGE
    );
    return { throughDate: legacyStatsThroughDate(archivePage.content) };
  } catch {
    return undefined;
  }
}

async function ensureLegacyStatsArchive(
  subredditName: string,
  currentStatsPage: StatsWikiPage
): Promise<LegacyStatsArchive | undefined> {
  const existingArchive = await loadExistingLegacyArchive(subredditName);
  if (existingArchive) {
    return existingArchive;
  }

  if (
    currentStatsPage.created ||
    !shouldArchiveStatsPage(currentStatsPage.content)
  ) {
    return undefined;
  }

  await reddit.createWikiPage({
    subredditName,
    page: ARTEMIS_LEGACY_STATS_PAGE,
    content: currentStatsPage.content,
    reason:
      'Archiving legacy Artemis statistics before Devvit statistics migration.',
  });
  await setStatsWikiPageSettings(subredditName, ARTEMIS_LEGACY_STATS_PAGE);

  return { throughDate: legacyStatsThroughDate(currentStatsPage.content) };
}

function buildAnnouncementSection(
  subredditName: string,
  legacyArchive?: LegacyStatsArchive
): string {
  const lines = [
    ARTEMIS_DEVVIT_STATS_MARKER,
    '*This page is generated by the Devvit port of Artemis. Some historical Python-era statistics are not available in this runtime.*',
  ];

  if (legacyArchive) {
    const throughDate = legacyArchive.throughDate
      ? ` through ${legacyArchive.throughDate}`
      : '';
    lines.push(
      '',
      `*Legacy Artemis statistics${throughDate} are archived at [${ARTEMIS_LEGACY_STATS_PAGE}](${legacyArchiveLink(
        subredditName
      )}).*`
    );
  }

  return lines.join('\n');
}

export async function initializeStatsWikiPage(
  subredditName: string
): Promise<void> {
  await ensureStatsWikiPage(subredditName);
}

export async function updateStatsWikiPage(
  subredditName: string
): Promise<void> {
  const compileStart = Date.now();
  const statsPage = await ensureStatsWikiPage(subredditName);
  const legacyArchive = await ensureLegacyStatsArchive(
    subredditName,
    statsPage
  );

  const [botStatusSection, postsSection, subscribersSection] =
    await Promise.all([
      collateBotStatusSection(),
      collatePostsSection(),
      collateSubscribersSection(),
    ]);

  const content = wikipageTemplate({
    subredditName,
    botStatusSection,
    postsSection,
    subscribersSection,
    trafficSection: collateTrafficSection(),
    versionNumber: ARTEMIS_STATS_VERSION,
    compileSeconds: ((Date.now() - compileStart) / 1000).toFixed(2),
    updatedAtUtc: timeConvertToString(nowSeconds()),
    announcementSection: buildAnnouncementSection(subredditName, legacyArchive),
    navigationPrefix: '',
  });

  await reddit.updateWikiPage({
    subredditName,
    page: ARTEMIS_STATS_PAGE,
    content,
    reason: `Updating with Devvit statistics data. Retained post snapshots: ${ARTEMIS_SETTINGS.statsPostRetention}.`,
  });
}

export async function updateStatsWikiPages(
  subredditNames: string[]
): Promise<void> {
  for (const subredditName of subredditNames) {
    await updateStatsWikiPage(subredditName);
  }
}
